### ISSUE TITLE
Update axios peer dependency

### ISSUE THREAD

**Issue by m-demydiuk** [christianmalek/vuex-rest-api#108]
Please update axios peer dependency to `^0.21`

**Comment by christianmalek** [comment]
Hi,

I'll do it in a few days.

**Comment by christianmalek** [comment]
Done in https://github.com/christianmalek/vuex-rest-api/commit/d1c3bbc8699624a8fc413312017b0dcd8457745d

**Comment by m-demydiuk** [comment]
@christianmalek Could you please update peer dependency again as latest axios version is 0.27.2.
And would be great to make it the way vuex-rest-api don't block updating axios :)

**Comment by christianmalek** [comment]
@m-demydiuk I'll update it in a few days! So how would you solve the problem with the peer dependency? Just remove the peer dependency and hope that everybody installed the proper version of axios?

**Comment by christianmalek** [comment]
Updated to newest axios version. Repo is updated and live on npm!

**Comment by m-demydiuk** [comment]
@christianmalek Thanks for the update. Regarding how to correctly set dependencies - I can't advise. Maybe like other package developers do :)
