### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by ghenry** [christianmalek/vuex-rest-api#109]
```
npm ERR! Found: axios@0.26.1
npm ERR! node_modules/axios
npm ERR!   axios@"^0.26.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer axios@"^0.21" from vuex-rest-api@2.14.0
npm ERR! node_modules/vuex-rest-api
npm ERR!   vuex-rest-api@"^2.14.0" from the root project
```

**Comment by christianmalek** [comment]
Hey,

vuex-rest-api requires `axios^0.21`. `axios^0.26.1` does not satisfy this version constraint. I have to update the version.

**Comment by ghenry** [comment]
I forget as it's been a while, but does ^ pin that version or mean anything greater than?

**Comment by christianmalek** [comment]
You can check it here https://jubianchi.github.io/semver-check/#/^0.21/0.26.1

**Comment by ghenry** [comment]
Thanks

**Comment by christianmalek** [comment]
Updated to the newest axios version. :)
