### ISSUE TITLE
Not possible to create a pr

### ISSUE THREAD

**Issue by m-demydiuk** [christianmalek/vuex-rest-api#111]
Hi @christianmalek.

We use your lib heavily in our projects. And all the time we have a problem with one thing. So now I decided to create a pr to extend functionality of the VAPI. However I  am not able to create a PR.

![image](https://github.com/christianmalek/vuex-rest-api/assets/2910327/cdf8e78a-f620-4a31-8802-af4f37525af1)

**Comment by christianmalek** [comment]
Hello Maksym,

I am glad that you are using the software. However, I haven't changed anything about pull requests. I guess the error is on your side or do you know if GitHub has made any changes in the default settings?

**Comment by m-demydiuk** [comment]
@christianmalek thanks for the quick reply. Should I fork your repo and create pr in the fork?

![image](https://github.com/christianmalek/vuex-rest-api/assets/2910327/c2bf07ed-5170-4946-ad80-2fbc697245c0)

UPD: created a pr via fork :)

**Comment by christianmalek** [comment]
I will probably look at the PR by the weekend. Thank you very much for your participation!
