### ISSUE TITLE
How to for concept of Vuex modules using

### ISSUE THREAD

**Issue by elceka** [christianmalek/vuex-rest-api#12]
Hi, please, can you write some hint or how to for using your library with Vuex concept of modules?
https://vuex.vuejs.org/en/modules.html

**Comment by christianmalek** [comment]
Hi @elceka,

If you want to modules, just create the resources, then create the stores and pass them to the `Vuex.Store` constructor like this:

```js
const postsResource= new Resource(/*...*/)
const usersResource = new Resouce(/*...*/)

const posts = createStore(postsResource)
const users = createStore(usersResource )

const store = new Vuex.Store({
  modules: {
    posts,
    store
  }
})
```

**Comment by christianmalek** [comment]
I'll close this issue. If you have any further queustions don't hesitate to ask.

**Comment by Hobbs1210** [comment]
Does the same method apply to 2.0 ?
Passing the created Vapi resource to vuex.store dose not seem to work.

**Comment by christianmalek** [comment]
I can only answer you from my mobile Phone at the moment.

Did you call the Vapi.getStore() method? Please see step 4 in https://github.com/christianmalek/vuex-rest-api/blob/v2/README.md#steps

**Comment by Hobbs1210** [comment]
Yes,  getStore() is called. The module shows up under $store.state, but it's empty.

**Comment by christianmalek** [comment]
I'll investigate this issue.

**Comment by christianmalek** [comment]
I created a new issue. Please continue the discussion here: https://github.com/christianmalek/vuex-rest-api/issues/24
