### ISSUE TITLE
create tests

### ISSUE THREAD

**Issue by christianmalek** [christianmalek/vuex-rest-api#15]

**Comment by christianmalek** [comment]
Add https://github.com/typicode/json-server for tests

**Comment by christianmalek** [comment]
Use circle-ci

**Comment by christianmalek** [comment]
Add Git precommit hook with transpiler and test runner, same procedure for city test

**Comment by marceloavf** [comment]
Is there some easy way to do unit tests with `vuex-rest-api` ?

**Comment by christianmalek** [comment]
@marceloavf I didn't think out anything yet. But since it's only a store creator you're able to use the standard vuex testing utilities (see async actions in https://vuex.vuejs.org/en/testing.html)

**Comment by slurmulon** [comment]
@christianmalek I'm happy to start writing some tests. I am using this module in a production application (about to be more than one!), so I have a vested interest in keeping things not broken :slightly_smiling_face: 

What testing frameworks do you prefer? I generally use `mocha`, but recently I've shifted more towards TAP frameworks such as `tape` since they avoid the weird environment and setup problems that you typically encounter with frameworks like `mocha` and `jasmine`.

**Comment by christianmalek** [comment]
Hello Erik,

I've used Jest with babel-jest. But feel free to use what you want. I would
appreciate it very much!

Erik Vavro <notifications@github.com> schrieb am Fr., 12. Okt. 2018, 21:34:

**Comment by slurmulon** [comment]
Great! I'll put some time towards it this weekend, although there will probably be some initial friction as I haven't played with unit tests in TypeScript yet.

**Comment by christianmalek** [comment]
Great! Thanks in advance.

Erik Vavro <notifications@github.com> schrieb am Sa., 13. Okt. 2018, 03:03:

**Comment by slurmulon** [comment]
So I didn't get to it as soon as I would have liked (ya know, because life stuff)... but I have started fleshing out more tests: https://github.com/slurmulon/vuex-rest-api/tree/tests

I will have more availability next week to really hammer on these :muscle:

**Comment by christianmalek** [comment]
Hello @slurmulon,

Please take your time and again: Thanks for your contribution.

**Comment by christianmalek** [comment]
@slurmulon Hey! Any news? :)

**Comment by christianmalek** [comment]
@slurmulon Ping

**Comment by christianmalek** [comment]
Already in progress by myself.
