### ISSUE TITLE
Why wrong in IE Browser

### ISSUE THREAD

**Issue by caizhiming8** [christianmalek/vuex-rest-api#17]
Error reporting in IE browser

**Comment by christianmalek** [comment]
Could you provide a screenshot?

**Comment by caizhiming8** [comment]
I do not use this plugin is not wrong.If i use this plugin IE browser to tell me is a syntax error, but google browser will not be given

**Comment by caizhiming8** [comment]
![2](https://cloud.githubusercontent.com/assets/24382557/25849938/0deb6946-34f3-11e7-90ab-ee4b4b76915a.png)
![Uploading 图片2.png…]()
![Uploading 图片2.png…]()

**Comment by christianmalek** [comment]
I don't know which version of Internet Explorer you are using. But it's possible that it doesn't support ES2015 language features. So you have to use a transpiler like babel.

**Comment by caizhiming8** [comment]
My browser is IE 11.Do you mean that I still need to install other plugins?If so, what kind of plugin should I install?

**Comment by caizhiming8** [comment]
yes thank you

**Comment by christianmalek** [comment]
I'll let you know when I publish it.

**Comment by christianmalek** [comment]
@caizhiming8 I've published a new version of the package. Please update and try it again.
