### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by sotaan** [christianmalek/vuex-rest-api#19]
Hi,

I try to create an API module which will be used by other modules in my store to ask for data then apply my business logic on top of it.
Here is my `api.js` file:
```
import Vue from 'vue'
import { createStore, Resource } from 'vuex-rest-api'

const options = {
  axios: Vue.axios
}
const resource = new Resource(__API_ROOT__, options)

// Auth (User and Guest cases)
resource
  .addAction({
    action: "login",
    method: "post",
    property: "token",
    pathFn: () => '/auth/login'
  })
  .addAction({
    action: "getGuestHash",
    method: "get",
    property: "guest_hash",
    pathFn: () => '/auth/get_guest_hash'
  })
// Cart
  .addAction({
    action: "getCart",
    method: "get",
    property: "cart",
    pathFn: (id) => `/carts/${id}`
  })
  .addAction({
    action: "createCart",
    method: "post",
    property: "cart",
    pathFn: () => `/carts`
  })
  .addAction({
    action: "cleanCart",
    method: "put",
    property: "cart",
    pathFn: () => `/carts/clean`
  })
  .addAction({
    action: "getActiveCart",
    method: "get",
    property: "activeCart",
    pathFn: () => `/carts/active`
  })
  .addAction({
    action: "changeDomiciliationOffer",
    method: "put",
    property: "cart",
    pathFn: (id) => `/carts/${id}`
  })
  .addAction({
    action: "addOffer",
    property: "cart",

  })

export default createStore(resource)
```

my `store/index.js` file:
```
import Vue from 'vue'
import Vuex from 'vuex'
import mutations from './mutations'
import actions from './actions'
import getters from './getters'
import api from './modules/api'

Vue.use(Vuex)

const state = {
  count: 0
}

const store = new Vuex.Store({
  state,
  mutations,
  actions,
  getters,
  modules: {
    api
  }
})

export default store
```

Here is the error I get from the console:
![capture d ecran 2017-05-10 a 15 13 03](https://cloud.githubusercontent.com/assets/9435918/25900323/5c117548-3593-11e7-98d8-ff658bea38c3.png)

**Comment by christianmalek** [comment]
I don't see any error in your code. I'll investigate this next week. At the moment I'm pretty busy.

**Comment by sotaan** [comment]
I just found that I needed to call my actions that way: `this.store.$dispatch('myaction', {})` to get it working.
Calling that way: `this.store.$dispatch('myaction', {})` will trigger the error.
I suggest that it must come from destructing assignment in your params in here:
[https://github.com/christianmalek/vuex-rest-api/blob/master/src/StoreCreator.ts#L97](storeCreator.ts)

try that:
`storeActions[dispatchString] = async ({ commit }, { params = {}, data = {} } = {}: ActionParamsBody) => { ...`

**Comment by christianmalek** [comment]
Thanks for figuring this out. I really need to create tests.

**Comment by christianmalek** [comment]
@sotaan I updated this package. Now it should also work without passing an empty object.

**Comment by christianmalek** [comment]
@sotaan I just saw another error in your code snippet. You have to destructure the params in the path fn. 
False:
```js
pathFn: (id) => `/carts/${id}` // false (id is the params object and not the id property
```
Correct:
```js
pathFn: ({id}) => `/carts/${id}`
