### ISSUE TITLE
silent errors

### ISSUE THREAD

**Issue by sotaan** [christianmalek/vuex-rest-api#22]
Using your module since 2 weeks I see in my projects that mutationFailureFn never got called even in case of failure. 
Instead, module will call mutationSuccessFn with an `undefined` as payload which causing me a lot of headaches trying to figure this out.
Putting some `.catch()`or error callback to my `.then()` don't work (I tried in many places).
I'm currently preparing you a fiddle demonstrating this behavior.

**Comment by christianmalek** [comment]
Which version are you using?

**Comment by sotaan** [comment]
V 1.0.2

David Mamane Full-Stack Web Developper, Admin Sys +33 (0)6 52 47 37 28 davidmamane@hellomojito.com [mickael@hellomojito.com]



Avis de confidentialité : Le contenu de ce document est juridiquement confidentiel. Il est réservé à l'usage de son destinataire. Ce document est couvert et protégé par le secret professionnel prévu et sanctionné par les dispositions de l'article 378 du Code Pénal.
via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.7.35&pv=10.3.1&source=email_footer_2]
On lun., mai 22, 2017 at 11:54, Christian Malek <notifications@github.com> wrote:
Which version are you using?

**Comment by christianmalek** [comment]
Which kind of error has been thrown?

**Comment by sotaan** [comment]
This happens mostly when my API is down (network error or connection aborted) or when timeout(connection aborted only) is reached

**Comment by christianmalek** [comment]
`vuex-rest-api` just catches the errors which will be thrown by `axios`. So this error should lie in the area of responsibility of `axios`.

**Comment by sotaan** [comment]
how can axios return you ok with an undefined payload ????

**Comment by christianmalek** [comment]
If axios doesnt identify the response as error, vuex-rest-api won't know.

**Comment by christianmalek** [comment]
Just let me know when your fiddle is ready. I really need more information.

**Comment by christianmalek** [comment]
@sotaan Did you find a solution to your problem?

**Comment by christianmalek** [comment]
I'll close this issue due to inactivity. If you think this is inappropriate feel free to issue it again.
