### ISSUE TITLE
Issue with using vuex-rest-api as store module

### ISSUE THREAD

**Issue by christianmalek** [christianmalek/vuex-rest-api#24]
See https://github.com/christianmalek/vuex-rest-api/issues/12

@Hobbs1210 Could you please provide a code snippet? I tried to use it as module and it works without problems.

**Comment by Hobbs1210** [comment]
@christianmalek issue has been resolved.I had a coding issue on my end. Thank you for your help.

**Comment by christianmalek** [comment]
Awesome!
