### ISSUE TITLE
How to change a mutation

### ISSUE THREAD

**Issue by marceloavf** [christianmalek/vuex-rest-api#30]
I'm trying to change a mutation that createStore has done, I found in the docs that this could execute someting when it success:

```js
  // This function will be called after successfully resolving the action.
  // If you define this property, only the corresponding
  // pending annmd error properties will be set, but not state[property].
  // The method signature is (state, error).
  mutationSuccessFn: Function,
```

But my problem is that I need to concat this state with the old one, is that possible?

Thanks!

**Comment by christianmalek** [comment]
Oops! There is an error in the documentation. I confound the comments for `mutationSuccessFn` and `mutationFailureFn`.

The method signature looks like `function (state, payload)`, so `state` is the store state and`payload` is the response from your API.

**Comment by marceloavf** [comment]
Is there a way to do it ? 
Or I need to do this inside another action/mutation?

```js
mutationSucessFn: (state, payload) => {
      this.state = this.state.concat(payload.data);
    },
```

Thank you!

**Comment by christianmalek** [comment]
Glad you found the error. :)
