### ISSUE TITLE
Alter body or header dynamically

### ISSUE THREAD

**Issue by leogout** [christianmalek/vuex-rest-api#36]
Hello, is there a way to change the body or the header of the request when it gets called such as the `pathFn` ?

A use case:
I dispatch a `"connexion"` action:
```js
this.$store.dispatch('connexion', {
  data: {
    _username: ...,
    _password: ...
  }
}
```
In this example, my component emitting the action is holding the request's body. If I change it here, I break the api call. If I have to transform it into a FormData() object, I have to do it in place into the component.

Is there a way to avoid this ? Can I do it in the Vapi store definition ?

By the way, thanks for this cool library !

Cheers.

**Comment by christianmalek** [comment]
Hi! Thanks for the compliment. Actually it's not possible at the moment. But I've already tracked this issue. See https://github.com/christianmalek/vuex-rest-api/issues/34

**Comment by leogout** [comment]
Oh sorry, I didn't found that issue...
I have some spare time this week, do you accept PRs ?

**Comment by christianmalek** [comment]
PRs are very welcome.

**Comment by leogout** [comment]
Hello, after a few attempts, I've come to the conclustion that it wouldn't be practical without breaking changes.
Sorry for that, I'll try again when I get more spare time.

**Comment by christianmalek** [comment]
I'll close this issue for now. Feel free to create a new issue if required.

**Comment by christianmalek** [comment]
@leogout Since version 2.8.0 it's possible to set headers dynamically.
