### ISSUE TITLE
Typescript unable to locate declaration file

### ISSUE THREAD

**Issue by dboune** [christianmalek/vuex-rest-api#38]
- Are you using the newest version of vuex-rest-api? `YES: 2.2.1`
- Did you read the README? `YES`
- Did you check the existing issues? Maybe there's already a solution to your problem. `YES`

Using typescript, though the module has `.d.ts` files, I receive the error:
> TS7016: Could not find a declaration file for module 'vuex-rest-api'

Adding a single line to `package.js` providing the path to index.d.ts seems to resolve the issue.
```js
  "types": "dist/index.d.ts"
```

**Comment by christianmalek** [comment]
Could you PR it?

**Comment by dboune** [comment]
I would be happy to.. I'll try to do that today, internet permitting. Fires in my area are making things a bit rough.

**Comment by christianmalek** [comment]
Oh. Hope you're doing good. :/
