### ISSUE TITLE
Improve catch error to return response

### ISSUE THREAD

**Issue by marceloavf** [christianmalek/vuex-rest-api#43]
When using axios itself, you can use `error.response` to get the response of an error, e.g.:
```js
axios.post('/formulas/create', {
	name: "",
	parts: ""
})
.then(response => { 
	console.log(response)
})
.catch(error => {
    console.log(error.response)
});
```

But right now it only return the scope of the error, e.g.:
```js
[error] Error: Network Error
    at createError (D:\xampp\htdocs\xxxx\node_modules\axios\lib\core\createError.js:16:15)
    at XMLHttpRequest.handleError (D:\xampp\htdocs\xxxx\node_modules\axios\lib\adapters\xhr.js:87:14)
```

Is there a way to change that or I'm doing something wrong?

Thanks!

**Comment by marceloavf** [comment]
Strange, seems to be something with axios https://github.com/axios/axios/issues/960
When response code is 500/401 it doesn't return a response.

**Comment by christianmalek** [comment]
Ah, ok. An other possibility would be that the error output is just "beuatified" by Chrome/etc. So you should just try to access the `error.response` property. I'll close this. Feel free to reopen it.

**Comment by MarcelBuian** [comment]
The error.response is undefined for me.
If I print error in console I get this:
```
Error: Network Error
    at createError (createError.js?16d0:16)
    at XMLHttpRequest.handleError (xhr.js?ec6c:88)
```
Is there any way to see the status and response ?

I am using "axios": "^0.17.0"
and Chrome on Windows, Version 61.0.3163.100 (Official Build) (64-bit)
