### ISSUE TITLE
Axios errors

### ISSUE THREAD

**Issue by ghenry** [christianmalek/vuex-rest-api#47]
Hi,

Related #34 and #35  The reason I'm asking is that the error object only shows:

state.error.<propertyName>: Error

No actual detail there, whereas on the console log I see:

Unhandled promise rejection 
Error: Request failed with status code 404
Stack trace:
createError@webpack-internal:///./node_modules/axios/lib/core/createError.js:16:15
settle@webpack-internal:///./node_modules/axios/lib/core/settle.js:18:12
handleLoad@webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:77:7

Thanks.

**Comment by christianmalek** [comment]
Hi!

As you can see in https://github.com/christianmalek/vuex-rest-api/blob/v2/src/Store.ts#L183 the Store just returns the rejected promise and that is what the script gets from Axios. Did you try to access it like written in https://github.com/axios/axios#handling-errors ? Maybe it's some "beautifying" from Chrome/Firefox/etc.

**Comment by ghenry** [comment]
Here's a bit of my code:

```
        <p>{{ support.error.response.data }}
        {{ support.error.response.status }}
        {{ support.error.response.headers }}</p>
        <p v-bind:class="{ 'bounceIn animated': support.pending.ip_address }">{{ support.ip_address["ip-address"] }}</p>
       </b-card>
      </div>
    </div>
</template>

<script>
import { mapState, mapActions } from 'vuex'

export default {
  name: 'DiagnosticsMyIPAddress',
  metaInfo: {
    // title will be injected into parent titleTemplate
    title: 'My IP Address'
  },
  created() {
    this.getIpAddress()
  },
  computed: mapState([
    'support'
  ]),
  methods: {
    ...mapActions([
        "getIpAddress"
    ])
  }   
}
</script>
```


Vuex object looks like 
![screenshot from 2018-02-05 22-01-19](https://user-images.githubusercontent.com/159608/35831063-5cfac560-0ac0-11e8-862d-9f6d0c8a6843.png)

**Comment by christianmalek** [comment]
I just tried it and it's how i've written. The browser sees the error and simplifies the output.

Also please have a further look at the data structure. You have to access e.g. `support.error.ip_address.response.status`.

**Comment by christianmalek** [comment]
By the way: If you don't like the "error bag", you could also use async-await:

```js
try {
  await this.$store.dispatch("createPost", {
    data: {
      title: 'foo',
      body: 'bar',
      userId: 1
    }
  })
} catch (error) {
  console.log(error)
}
```

**Comment by ghenry** [comment]
It's so weird. I see the red Error which means this `support.error.ip_address.response.status` should work, but I get this:
`
[Vue warn]: Error in render: "TypeError: _vm.support.error.ip_address.response is undefined" found in ---> <DiagnosticsMyIPAddress> at src/components/Diagnostics/MyIPAddress.vue <Container> at src/components/Layouts/Container.vue <App> at src/App.vue <Root>`

**Comment by ghenry** [comment]
Helps if I could read!!! .response is Empty as only the .message is set.

![screenshot from 2018-02-05 22-47-34](https://user-images.githubusercontent.com/159608/35832860-b4adcc5c-0ac6-11e8-82d8-295edadf4a88.png)

**Comment by christianmalek** [comment]
Please close the issue if your problem is solved.
