### ISSUE TITLE
Returned promise from HTTP PUT method catch error on success response (v2)

### ISSUE THREAD

**Issue by elceka** [christianmalek/vuex-rest-api#48]
Hi,
i have problem with returned promise (probably from Axios?) on success PUT request with HTTP status code 200. Promise catching error, but i don't know why. If i try pure Axios with PUT method, then returned promise is OK. Before some days i update packages of my project (latest vuex-rest-api and required Axios version), but i don't know, if is this a problem.

**Comment by christianmalek** [comment]
Hi elceka,

Please try to use an older axios version with the current vuex-rest-api.

**Comment by elceka** [comment]
I've renewed node_modules directory after trying some lower versions of Axios and vuex-rest-api and after that it is OK... :worried:

**Comment by christianmalek** [comment]
I tried yesterday the newest version of vuex-rest-api and Axios and had no problems. Sorry, I can't reproduce this failure. :(
