### ISSUE TITLE
Write proper documentation

### ISSUE THREAD

**Issue by christianmalek** [christianmalek/vuex-rest-api#5]
The documentation is mandatory. Otherwise the different API combinations won't be understandable.

**Comment by apertureless** [comment]
[docute](https://github.com/egoist/docute) is pretty nice and works out of the box.

**Comment by christianmalek** [comment]
Thanks. I'll check it out!

**Comment by christianmalek** [comment]
At the moment I see no need for "better" documentation. I'll close this issue.
