### ISSUE TITLE
Strange case of double-promise in production

### ISSUE THREAD

**Issue by wc-matteo** [christianmalek/vuex-rest-api#52]
While developing locally, `this.$store.dispatch('...')` returns a promise. When the code is in production, it returns a promise that returns a promise (I need to use `await await this.$store.dispatch('...')`). Any idea why that is?

**Comment by christianmalek** [comment]
I have no idea. Sorry.

**Comment by christianmalek** [comment]
Maybe I could help if you provide a code snippet.

**Comment by wc-matteo** [comment]
Thanks. I'll try to recreate a minimal repro.

**Comment by wc-matteo** [comment]
Discovered the cause:

Taking out `"plugins": ["transform-runtime"]` from `.babelrc`, makes production code have the double promise.
(I removed the transform runtime, because I'm using babel polyfill)

**Comment by christianmalek** [comment]
Glad you found it. 👍
