### ISSUE TITLE
Id Parameter is always undefined 

### ISSUE THREAD

**Issue by Vad1mo** [christianmalek/vuex-rest-api#55]
I have this action definition

```js
  .get({
    action: 'getUser',
    property: 'user',
    path: ({ id }) => {
      console.log('The Arg is ', id)
      return `/tenants/${id}`
    }
  })
```

And I am dispatching like this:

Try 1:
```
js
created: function () {
        this.$store.dispatch({
        type: 'getUser',
        data: { id: this.$route.params.id }
      })
```

Try 2:
```
js
created: function () {
      this.$store.dispatch('getUser', {
        data: {
          id: 1
        }
      })
```

Try 3:
```
js
created: function () {
      this.$store.dispatch('getUser', { id: 1243 }, null )
```

In all cases the id is undefined. IMHO it should have an id.

**Comment by christianmalek** [comment]
Hi Vadim,

There is another property `params`. Please see https://github.com/christianmalek/vuex-rest-api#calling-the-actions

**Comment by christianmalek** [comment]
@Vad1mo I've updated my answer.

**Comment by Vad1mo** [comment]
thank you for the quick response, this works perfectly. The example would be a perfect candidate for the readme :)
What confused me was this syntax `getPost({params: {someParam: 5, anotherParam: "foo"}})` it wasn't introduced (at least in the quick start) before as action and arguments.
