### ISSUE TITLE
Broken type definitions for getStore

### ISSUE THREAD

**Issue by gcbirzan** [christianmalek/vuex-rest-api#67]
`Vapi.getStore` is declared as returning a `Store` object, but if you pass `createStateFn: false`, that's not the case.

First of all, I think that API is silly. There should be a different function, maybe `getStoreObject` that abstracts this. But, even if you don't agree with that idea, the type definition needs to be updated.

**Comment by christianmalek** [comment]
I'll close this issue. Feel free to reopen it.
