### ISSUE TITLE
Problem recreating example from docs

### ISSUE THREAD

**Issue by arjanski** [christianmalek/vuex-rest-api#68]
Hello,

First of all thank you for this great helper tool. I'm having troubles using it (see below), but looks just like what my project needs. I hope a noob question is okay:

When I try recreating the example code from the docs, vue devtools show me a state with empty objects (e.g. `posts: Array[0]`, ``pending: ... post: false ... ). 

I've set up a new Vue project using vue-cli 3, installed vuex-rest-api 2.8 and axios 0.18.

My store.js

```
import Vuex from "vuex"
import Vue from "vue"
// Step 1
import Vapi from "vuex-rest-api"

Vue.use(Vuex)

// Step 2
const posts = new Vapi({
  baseURL: "https://jsonplaceholder.typicode.com",
    state: {
      posts: []
    }
  })
  // Step 3
  .get({
    action: "getPost",
    property: "post",
    path: ({ id }) => `/posts/${id}`
  })
  .get({
    action: "listPosts",
    property: "posts",
    path: "/posts"
  })
  .post({
    action: "updatePost",
    property: "post",
    path: ({ id }) => `/posts/${id}`
  })
  // Step 4
  .getStore()

// Step 5
export const store = new Vuex.Store(posts)
```

the <script> section of my Home.vue where I'd like to display the test data:

```
<script>
import store from "../store"
import {mapState, mapActions} from 'vuex'

export default {
  name: 'home',
  computed: mapState([
    'posts'
  ]),
  created() {
    this.listPosts()
  },
  vuex: {
    getters: {
    }
  },
  methods:{
  }
}
</script>
```

Could anyone point out the error(s) in my setup? I'm new to Vuex and would love an easy access to our REST API using this tool. 

Thank you in advance!

**Comment by christianmalek** [comment]
Hey!

You also have to map the actions to be able to use it with `this.<methodeName>`. See https://vuex.vuejs.org/guide/actions.html#dispatching-actions-in-components

**Comment by arjanski** [comment]
Wow, thanks for that lightning quick response 👍 

So I guess it was a noob question and not my usage of vapi. Mapping the actions didn't do the trick (yet), but I'll investigate some more. Thanks again!

**Comment by christianmalek** [comment]
OK. Then you also didn't register your vuex store properly. Please look at this example: https://github.com/vuejs/vuex/tree/dev/examples/counter

Specifically look at this file: https://github.com/vuejs/vuex/blob/dev/examples/counter/app.js

You don't have to import the store in your `Home.vue` file. Therefore you need to import it in your `app.js` file and set it as property from your new Vue instance. :)

**Comment by arjanski** [comment]
Thanks once again, makes sense. I took out the store reference from Home.vue, my app.js (created automatically by vue cli) should work

```
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'

Vue.config.productionTip = false

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount('#app')

```

There's still something wrong, but just shows me that I need to study the vuex docs more carefully. Thank you again for pointing all this out 👍

**Comment by christianmalek** [comment]
No problem! Maybe just try to grasp the concepts of Vuex first with one of their examples and then add vuex-rest-api. I think this will make your life a lot easier.
