### ISSUE TITLE
Optimistic updates - beforeRequest

### ISSUE THREAD

**Issue by BorisTB** [christianmalek/vuex-rest-api#70]
Hi,
first of all, thank you for this amazing tool.

There's just one thing I miss in this library.. is it possible to implement option to do changes to store before request is sent? E.g. I want to delete table row in view as soon as users clicks on delete, and if request fails then I'll add that row back to store.

Something like beforeRequest or optimisticUpdate option.

**Comment by BorisTB** [comment]
I'm not really skilled with typescript, but this works for me:
https://github.com/christianmalek/vuex-rest-api/pull/71/files

**Comment by christianmalek** [comment]
Hey! Thanks for your PR. I'll test it and respond to you in ~1 week.

**Comment by christianmalek** [comment]
I've merged it. Thanks again for your contrib!
