### ISSUE TITLE
[QUESTION] - Pre API Call Transformation

### ISSUE THREAD

**Issue by go4cas** [christianmalek/vuex-rest-api#77]
First off ... awesome library!

I want to know if there is a way of transforming the request payload before calling the API? At present I can use `OnSuccess` to transform the response payload I get back from my back-end API, but for my use case I need to transform the payload, before `POST` and `PUT` requests.

**Comment by go4cas** [comment]
Okay, I see that in `2.9.0` a new `beforeRequest` was introduced. I'm just not sure how to change the data object using this. Or, should I rtaher do the transformation in `requestConfig` -> `transformResponse`?

**Comment by go4cas** [comment]
I got it working by using `beforeRequest`, and setting the `state` object to the "write format", as opposed to the `data` object. I then update the state object to the "view format" in the `onSuccess`. Is this the optimal way of achieving my use case? Or, is there a better way of doing this?

**Comment by christianmalek** [comment]
Hey @go4cas !
The `beforeRequest` method was added to update your store optimistically (before you got the response from the server with the actual data).

If you need to transform your data doing it via `requestConfig.transformRequest` is at the moment the proper way to go. Mhm. Maybe I should another method to do this without fiddling in the requestConfig`. 🤔

**Comment by christianmalek** [comment]
I'll close this. Feel free to open an new issue.
