### ISSUE TITLE
Axios request config params object

### ISSUE THREAD

**Issue by elceka** [christianmalek/vuex-rest-api#8]
Hi,
how can i use Axios request config params object for Resource object actions?
Action of Resource object has function **pathFn** for adding some parameters to the URL, but i need add some handy parameters with stringifying needing and Axios has **paramsSerializer** function for that (usable with Qs library). Please, how can i use Axios paramsSerializer function with your helper?

Resource object wrapper with configured Axios instance and paramsSerializer option:
````javascript
import Qs from 'qs'
import Axios from 'axios'
import { Resource } from 'vuex-rest-api'

export default class ResourceWrapper {
    constructor(baseURL = null, options = {}) {
        baseURL = baseURL || 'http://localhost:8003/api/admin'
        options.axios = Axios.create({
            paramsSerializer: function(params) {
                return Qs.stringify(params, {arrayFormat: 'indices'})
            }
        })

        return new Resource(baseURL, options)
    }
}
````

**Comment by christianmalek** [comment]
You can pass each action a request config. The property's name is `requestConfig`.

Example:
```js
  resource.addAction({
    action: "get",
    method: "get",
    property: "post",
    pathFn: ({ id }) => `/posts/${id}`,
    requestConfig: {
            paramsSerializer: function(params) {
                return Qs.stringify(params, {arrayFormat: 'indices'})
            }
    }
});

**Comment by elceka** [comment]
Thank you for fast reply, but that solutions (yours and my) wont work. HTTP request is without params of the URL.

**Comment by christianmalek** [comment]
I'll investigate this issue later today.

**Comment by christianmalek** [comment]
@elceka Please update your npm package.

**Comment by elceka** [comment]
Thank you, its working.
But now, all actions have set request config, but i set this option only in action for list of models.

Example of store:

````javascript
import { stringify } from 'qs'
import { createStore } from 'vuex-rest-api'
import ResourceWrapper from './../ResourceWrapper'

const resource = new ResourceWrapper()
    .addAction({
        action: 'listModels',
        method: 'get',
        property: 'models',
        pathFn: () => `/models`,
        requestConfig: {
            paramsSerializer: function (params) {
                return stringify(params, {arrayFormat: 'indices'})
            }
        }
    })
    .addAction({
        action: 'getModel',
        method: 'get',
        property: 'model',
        pathFn: ({ id }) => `/models/${id}`
    })
    .addAction({
        action: 'createModel',
        method: 'post',
        property: 'model',
        pathFn: () => `/models`
    })

const models = createStore(resource)

export default models
````

Produced URL for getting one model:
````http
GET http://localhost:8003/api/admin/models/45c6d991-34fc-321f-a2e2-3b921b35a6a1?id=45c6d991-34fc-321f-a2e2-3b921b35a6a1
````

**Comment by elceka** [comment]
Issue is on this new line of code from Resource class:
````javascript
const requestConfig = Object.assign({}, options.requestConfig, { params: params });
````
Maybe, params object should not be set if requestConfig object is empty.

**Comment by elceka** [comment]
Thank you again, it is working, all is only about implementation.

**Comment by christianmalek** [comment]
> Maybe, params object should not be set if requestConfig object is not contain paramsSerializer function.

Great idea. I'll change this tomorrow and let you know!
