### ISSUE TITLE
Correct way to change state

### ISSUE THREAD

**Issue by Tropicalista** [christianmalek/vuex-rest-api#83]
What is the correct way to change state property? I'm trying:

```
  .delete({
    action: 'deleteKey',
    property: 'key',
    path: ({ id,key }) => `/keys/${id}/${key}`,
    onSuccess: (state, payload, axios) => {
      // if you set the onSuccess function you have to set the state manually
      state.keys = state.keys.filter(key => key.id !== id);
    }
  })
```

**Comment by christianmalek** [comment]
Hey @Tropicalista,

this is the correct way. Doesn't it work?

**Comment by Tropicalista** [comment]
No it doesn't work...state does not change

**Comment by Tropicalista** [comment]
Do you have any codesandbox template that I can use to show you my code?

**Comment by christianmalek** [comment]
I've created a simple example for you: https://codesandbox.io/s/6woq3156pn

**Comment by Tropicalista** [comment]
Here's my code: https://codesandbox.io/s/oj247r3y9z

**Comment by christianmalek** [comment]
`id` is not in the scope of `onSuccess`. At the moment it's *not* easily possible to access the params. Please read here for more information: https://github.com/christianmalek/vuex-rest-api/issues/79

If possible you could just return the id via the response and access it with the payload. Then you could do sth. like this:

```js
onSuccess(state, payload, axios) {
  const id = payload.data.id // assumes you are returning id in the response
  state.posts = state.posts.filter(post => post.id != id);
}
```

**Comment by Tropicalista** [comment]
I will find another solution.
Thanks!

**Comment by christianmalek** [comment]
No problem!

**Comment by christianmalek** [comment]
Please update vuex-rest-api to v2.10.0. I've added the `{params, data}` as additional parameter in the `onSuccess` and `onError` functions so you can access now these properties.
