### ISSUE TITLE
Add support of mapping response object to typed model objects

### ISSUE THREAD

**Issue by Koc** [christianmalek/vuex-rest-api#85]
It would be nice add support mapping response to typed classes. Maybe reuse existent sollution like https://github.com/jf3096/json-typescript-mapper .  Also serialize typed request payloads to plain json.

We can get self-documented methods, request payloads and autocomplete for return types.

**Comment by christianmalek** [comment]
Hey @Koc,

I'll consider it. Thanks for your idea!

PRs are by the way very welcome.
