### ISSUE TITLE
Section "calling-the-actions" disapeared from the docs

### ISSUE THREAD

**Issue by andresmrm** [christianmalek/vuex-rest-api#86]
Hello again!

Nothing happens when I click `here` in "Continue reading here to know how to call the actions."
https://christianmalek.github.io/vuex-rest-api/how-to-use.html#calling-the-actions
But I think I remember this section from before...

**Comment by andresmrm** [comment]
Oh, it's indeed here:
https://christianmalek.github.io/vuex-rest-api/miscellaneous.html#calling-the-actions
So it's just a broken link.

**Comment by christianmalek** [comment]
Oh. I forgot to "fix" the links in the new docs. The section you're looking for is now here: https://christianmalek.github.io/vuex-rest-api/miscellaneous.html#calling-the-actions
