### ISSUE TITLE
Add ability to add "namespaced" option for "getStore"

### ISSUE THREAD

**Issue by geiseri** [christianmalek/vuex-rest-api#94]
In some cases, you want to have to have your API states in a module you need to supply a `namespaced: true` option.  Right now I have to do `modules: {api: {namespaced: true, ...api}}` and I would rather be able to do a `modules: {api}` for less verbosity.

**Comment by christianmalek** [comment]
Hello @geiseri,

Thanks for your idea! I've added it to the feature ideas for v3.

**Comment by wobsoriano** [comment]
Hi, may I know how you guys currently do namespacing with this? Thank you!

**Comment by christianmalek** [comment]
Hello @sorxrob I didn't add a namespacing option yet. This is why @geiseri 's method is currenty the way to go. PRs are welcome if you want to implement it.

**Comment by christianmalek** [comment]
Added in #99
