### ISSUE TITLE
How to get rid of error&pending in setting a custom state?

### ISSUE THREAD

**Issue by hamzamihaidanielx** [christianmalek/vuex-rest-api#95]

**Comment by christianmalek** [comment]
Could you please elaborate?

**Comment by hamzamihaidanielx** [comment]
![image](https://user-images.githubusercontent.com/12731515/62426319-e1994980-b6eb-11e9-8cc3-a228b749a61b.png)

Like, i was telling, uhm, basically i want for my store there, the object just to have the property **constants** and nothing more, **no pending or error properties**. Is this possible somehow?

Thank you kindly :)

**Comment by christianmalek** [comment]
Oh. Sorry, that's not possible at the moment. `error` and `pending` will be created automatically.

**Comment by hamzamihaidanielx** [comment]
> Oh. Sorry, that's not possible at the moment. `error` and `pending` will be created automatically.

Ah, i see. Well its not that bad tho, but would've been nice to actually have the store without them, maybe the next version, to be optional? I do not know. 

Either way, thank you so much for this library, makes things way easier :). Hope this stays active in further development, its really great.

**Comment by christianmalek** [comment]
I've added it to v3! Unfortunately I don't have much time at the moment to do any "nice-to-have" changes to the library.

Thanks for your kind words. :)

**Comment by hamzamihaidanielx** [comment]
> I've added it to v3! Unfortunately I don't have much time at the moment to do any "nice-to-have" changes to the library.
> 
> Thanks for your kind words. :)

Saw the v3 branch is behind compared to v2 in commits tho.

**Comment by christianmalek** [comment]
It's on a local branch.^^
