### ISSUE TITLE
Update peer dependency of axios

### ISSUE THREAD

**Issue by carbontwelve** [christianmalek/vuex-rest-api#96]
It might be an idea to update the peer dependency of axios to include `^0.19`

**Comment by christianmalek** [comment]
Thanks for the info. Wanna create a PR for it?

**Comment by ilyaryabchinski** [comment]
Hey @christianmalek ! Could you please check my PR on the issue #97 ?

**Comment by carbontwelve** [comment]
Thank you @ilyaryabchinski; I would have done this myself but its been a super busy week at work.
